- name: Restart Site24x7 Agent if down (remote)
  hosts: Host_group
  become: yes
  gather_facts: no

  tasks:
    - name: Check service status
      ansible.builtin.shell: systemctl is-active site24x7monagent.service
      register: svc_status
      failed_when: false
      changed_when: false

    - name: Restart service if inactive
      ansible.builtin.shell: systemctl restart site24x7monagent.service
      when: svc_status.stdout != "active"
