---
- name: Ensure Site24x7 Agent service is running on host
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  tasks:

    - name: Gather all service facts
      ansible.builtin.service_facts:

    - name: Debug current Site24x7 Agent service state
      debug:
        msg: >
          Current state of site24x7monagent.service is
          {{ ansible_facts.services['site24x7monagent.service'].state
             if 'site24x7monagent.service' in ansible_facts.services else 'not found' }}

    - name: Restart Site24x7 Agent if it is not running
      ansible.builtin.systemd:
        name: site24x7monagent.service
        state: restarted
      when:
        - "'site24x7monagent.service' in ansible_facts.services"
        - ansible_facts.services['site24x7monagent.service'].state != 'running'

    - name: Verify Site24x7 Agent service status after restart
      ansible.builtin.command: systemctl status site24x7monagent.service
      register: svc_status
      ignore_errors: yes

    - name: Show final service status
      debug:
        var: svc_status.stdout_lines
