- name: Restart Site24x7 Agent service
  hosts: Host_group
  become: yes

  tasks:
    - name: Restart Site24x7 Agent
      ansible.builtin.service:
        name: site24x7monagent
        state: restarted
