- name: Check if the Site24x7 Agent service is running, restart if down
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Restart Site24x7 Agent if not running
      command: sudo /bin/systemctl restart site24x7monagent.service
      when:
        - "'site24x7monagent.service' in ansible_facts.services"
        - ansible_facts.services['site24x7monagent.service'].state != 'running'

    - name: Debug service status
      command: systemctl status site24x7monagent.service
      register: svc_status
      ignore_errors: yes

    - debug:
        var: svc_status.stdout_lines
